.github/workflows/python-release.yml
.github/workflows/rust-test.yml
Cargo.lock
python/Cargo.toml
rust/Cargo.toml
rust/minidfs/src/main/java/Main.java
rust/src/client.rs
rust/src/error.rs
rust/src/file.rs
rust/src/hdfs/datanode.rs
rust/src/hdfs/ec.rs
rust/src/hdfs/mod.rs
rust/tests/common/ec.rs
rust/tests/common/mod.rs

Resolves #2
Caveat: relies on forked https://github.com/rust-rse/reed-solomon-erasure. If https://github.com/rust-rse/reed-solomon-erasure/pull/108 gets merged we can support this in any downstream Rust builds. Currently this will only work for the Python build that relies on the fork.

Support RS erasure decoding

---

.github/workflows/rust-test.yml
Cargo.lock
README.md
rust/Cargo.toml
rust/src/minidfs.rs
rust/tests/common/mod.rs
rust/tests/test_ec.rs
rust/tests/test_integration.rs

Came across the `serial_test` crate, which is a lot cleaner of a method for running the tests one by one than requiring the use of `--test-threads=1`

Use serial_test instead of requring test-threads=1

---

python/src/error.rs

- Use debug formatted string for default error conversion
- Only convert errors with direct python error types, and let everything else just fall through

Update Python error conversions

---

rust/src/file.rs
rust/tests/common/mod.rs

Added a test case to see if there was an underlying bug based on the test failure in https://github.com/Kimahriman/hdfs-native/pull/28. Didn't find the same issue but uncovered a separate bug

Fix edge case of reading at the start of a block

---

rust/src/file.rs
rust/src/hdfs/datanode.rs
rust/src/object_store.rs
rust/tests/common/mod.rs

Resolves #33 
Exposes a new FileReader method `read_range_stream` that returns a `Stream<Result<Bytes>>`. This lets you load large chunks (or all) of a file in chunks without having to load the whole thing into memory at once.
Existing read functions were updated to just work of this new method as a base, and are simply helper methods to get a full single buffer of data.
The object store `get` and `copy` methods were updated to use this new streaming method.

Stream reading support

---

.github/workflows/rust-test.yml
Cargo.lock
Cargo.toml
README.md
python/Cargo.toml
rust/Cargo.toml
rust/benches/ec.rs
rust/src/client.rs
rust/src/ec/gf256.rs
rust/src/ec/matrix.rs
rust/src/ec/mod.rs
rust/src/error.rs
rust/src/file.rs
rust/src/hdfs/datanode.rs
rust/src/hdfs/mod.rs
rust/src/lib.rs
rust/tests/test_ec.rs

Custom reed-solomon decoding

---

rust/src/hdfs/proxy.rs

ignore failure if `msync` not found, to support older hdfs versions

---

crates/hdfs-native/src/client.rs
crates/hdfs-native/src/hdfs/protocol.rs
crates/hdfs-native/tests/test_integration.rs

Make create with overwrite a little more user friendly and allow creating a file if it doesn't already exist. This is what other file systems typical behavior would be.
Also makes WriteOptions a little more user friendly with helper functions that can be chained, and `create` takes an `impl AsRef<WriteOptions>` now so a borrowed value can be passed in.

Create with overwrite creates file if it doesn't exist

---

crates/hdfs-native/tests/common/mod.rs
crates/hdfs-native/tests/test_integration.rs
crates/hdfs-native/tests/test_read.rs
crates/hdfs-native/tests/test_write.rs

Create dedicated read and write tests to speed up overall test time

---

README.md
crates/hdfs-native/build.rs

Follow up to https://github.com/Kimahriman/hdfs-native/pull/75, remove the need for `integration-test` feature for running benchmarks

Only need benchmark feature to run benchmarks

---

README.md
crates/hdfs-native/examples/simple.rs

Add simple example

---

Cargo.lock
crates/hdfs-native/Cargo.toml
crates/hdfs-native/benches/io.rs
crates/hdfs-native/src/hdfs/connection.rs

Using flamegraph, I discovered that most of the read/write time was spent doing CRC calculations. Using the new beta of the `crc` crate and it's `slice16` support, this greatly increases the CRC throughput which in turn greatly speeds up the read and write throughput. The read throughput is now equal to or slightly higher than the libhdfs method. The write is still a little behind, need to look into that more.

Use faster CRC implementation

---

Cargo.lock
Cargo.toml
crates/hdfs-native-object-store/Cargo.toml
crates/hdfs-native/Cargo.toml
crates/hdfs-native/src/hdfs/block_reader.rs
crates/hdfs-native/src/hdfs/block_writer.rs
crates/hdfs-native/src/hdfs/connection.rs
crates/hdfs-native/src/security/gssapi.rs

Resolves #79 
Adds a static DataNode connection cache with a three second expiry, the default the Hadoop client uses. Connections are only purged from the cache when a connection is retrieved from the cache, and we will try up to three cached connections before falling back to creating a new connection. This should help speed up multiple reads to the same file/DataNode in fast succession.

Support DataNode connection reuse

---

README.md
crates/hdfs-native/Cargo.toml
crates/hdfs-native/minidfs/src/main/java/main/Main.java
crates/hdfs-native/src/hdfs/block_reader.rs
crates/hdfs-native/src/hdfs/block_writer.rs
crates/hdfs-native/src/hdfs/connection.rs
crates/hdfs-native/src/minidfs.rs
crates/hdfs-native/src/security/sasl.rs
crates/hdfs-native/src/security/user.rs
crates/hdfs-native/tests/test_ec.rs
crates/hdfs-native/tests/test_integration.rs
crates/hdfs-native/tests/test_viewfs.rs
crates/hdfs-native/tests/test_write_resiliency.rs

Add support for datanode sasl negotation

---

python/Cargo.toml

To make Kerberos an optional feature for python package, and make it consistent with both hdfs-native and hdfs-native-object-store:
- Remove the explicit "kerberos" feature from the `hdfs-native` dependency declaration in Cargo.toml.
- Add a new feature named "kerberos", allowing the "kerberos" feature to be optionally enabled for the Python package.

feat: Configure optional `kerberos` feature for Python package

---

.github/workflows/python-release.yml
.github/workflows/python-test.yml
Cargo.lock
Cargo.toml
crates/hdfs-native/Cargo.toml
python/Cargo.toml

After https://github.com/Kimahriman/hdfs-native/pull/91, update CI to test and deploy kerberos feature, and use workspace versions for Python cargo deps

Conslidate Python deps with workspace and update CI to deploy Kerberos feature

---

crates/hdfs-native/minidfs/src/main/java/main/Main.java
crates/hdfs-native/src/hdfs/connection.rs
crates/hdfs-native/src/minidfs.rs
crates/hdfs-native/src/security/digest.rs
crates/hdfs-native/src/security/sasl.rs
crates/hdfs-native/tests/test_integration.rs

Part of https://github.com/Kimahriman/hdfs-native/issues/89
Adds cipher support to data transfer connections, and supports 128, 192, and 256 bit AES encryption

Add support for encrypting data transfers with AES

---

python/hdfs_native/__init__.py
python/hdfs_native/_internal.pyi
python/hdfs_native/fsspec.py
python/src/lib.rs
python/tests/test_fsspec.py
python/tests/test_integration.py
rust/src/client.rs
rust/src/hdfs/protocol.rs
rust/tests/test_integration.rs

Add getContentSummary support

---

README.md
rust/src/client.rs
rust/src/common/config.rs
rust/src/hdfs/proxy.rs
rust/src/security/gssapi.rs

Add support for `dfs.client.failover.resolve-needed`

---

rust/src/error.rs

Add more output to errors

---

rust/src/hdfs/proxy.rs

Don't log a warning on a retriable RPCError

---

rust/minidfs/src/main/java/main/Main.java
rust/src/hdfs/connection.rs
rust/src/hdfs/protocol.rs
rust/src/hdfs/proxy.rs
rust/src/security/sasl.rs

Better observer namenode support

---

python/pyproject.toml
python/src/lib.rs
python/tests/test_benchmark.py
rust/src/client.rs

Resolves #152 
Release GIL when possible for calls into Rust from Python. Added a benchmark to test the performance improvement for this as well.

Release GIL

---

python/hdfs_native/fsspec.py
python/tests/test_fsspec.py

Fsspec buffered reading

---

python/hdfs_native/fsspec.py
python/tests/test_fsspec.py
rust/src/client.rs
rust/src/hdfs/proxy.rs
rust/src/lib.rs

Allow using default fs for fsspec and pass storage options to client

---

rust/src/security/sasl.rs
rust/src/security/user.rs

Filter out expired tokens

---

rust/src/hdfs/block_reader.rs

Don't panic if a whole read isn't consumed

---

python/hdfs_native/cli.py
python/pyproject.toml
python/tests/test_cli.py

Resolves #172 and resolves #173 
Adds a new CLI module and creates a script link for `hdfsn`. Adds `mv` as the initial supported command.

Add initial CLI with mv command

---

python/hdfs_native/cli.py
python/pyproject.toml
python/tests/test_cli.py

Resolves https://github.com/Kimahriman/hdfs-native/issues/175

Add cat to CLI

---

Cargo.lock
Cargo.toml
python/Cargo.toml
python/conftest.py
python/hdfs_native/__init__.py
python/hdfs_native/_internal.pyi
python/hdfs_native/cli.py
python/src/lib.rs
python/tests/test_cli.py
python/tests/test_integration.py
rust/Cargo.toml

Resolves #193 
Includes adding a new method to the Python read, `read_range_stream`, to return an iterator of bytes of a range of the file

Add get to CLI

---

python/hdfs_native/cli.py
python/tests/test_cli.py

Add rm to CLI

---

python/hdfs_native/cli.py
python/tests/test_cli.py

Add touch to CLI

---

python/tests/test_cli.py

The `test_ls` for the CLI test seems flaky, and my best guess is the files and dirs are created so fast they have the same millisecond timestamp stored in HDFS, so the sorting is then non-deterministic. Just add a short sleep to try to address this

Add short sleeps to make ls test deterministic

---

rust/src/file.rs

Resolves #211 
Previously, in `read_range_buf`, the code passed `buf.len()` directly to `read_range_stream`, which could trigger a "Cannot seek beyond the end of a file" panic when the buffer size plus offset exceeded the file length:
```rust
if pos > self.file_length() {
panic!("Cannot seek beyond the end of a file");
}
```
This PR fixes the issue by calculating the safe read length as `min(buf.len(), self.file_length() - offset)`, ensuring we never attempt to read beyond the file boundaries.

fix: prevent panic in FileReader when buffer size exceeds file length.

---

rust/src/client.rs
rust/src/file.rs
rust/src/hdfs/block_writer.rs

Instead of creating a single config on the client instance, support passing the config around so different parts of the code can pull whatever configs it needs without other parts of the code needing to know about it

Store and pass around the config object

---

rust/minidfs/pom.xml
rust/src/client.rs
rust/src/file.rs
rust/src/hdfs/protocol.rs
rust/tests/test_integration.rs

Resolves #216 
`getLocatedFileInfo` was added in Hadoop 3.1. Simply use `getBlockLocations` instead which provides the same necessary information to be compatible with older Hadoop versions

Switch RPC call for file reads

---

rust/src/minidfs.rs

The test failure I was seeing was due to mvn not existing, java had been there the whole time :upside_down_face:

Correct expect error string

---

rust/src/common/config.rs
rust/src/security/sasl.rs

Fix: "All DataNodes failed" in kerberized env if dfs.data.transfer.protection not set.
Discussed in:
https://github.com/Kimahriman/hdfs-native/issues/258

Disable SASL for DataNodes if dfs.data.transfer.protection not set
