Kimahriman/hdfs-native

- .github/workflows/python-release.yml
- .github/workflows/python-test.yml
- .github/workflows/rust-test.yml
- Cargo.lock
- README.md
- rust/Cargo.toml
- rust/build.rs
- rust/src/hdfs/ec.rs
- rust/src/proto/hadoop.common.rs
- rust/src/proto/hadoop.hdfs.rs
- rust/src/proto/mod.rs
- rust/tests/common/minidfs.rs
- rust/tests/common/mod.rs
Resolves #15 
- Pre-generate protobuf bindings
- Use pre-generated gsasl bindings
> Speed up build

- rust/build.rs
- rust/src/error.rs
- rust/src/file.rs
- rust/src/object_store.rs
- rust/tests/common/mod.rs
Fix some issues that came up while trying to integrate with delta-rs
> Objectstore fixes

- rust/src/error.rs
- rust/src/hdfs/connection.rs
- rust/src/hdfs/datanode.rs
- rust/src/hdfs/protocol.rs
- rust/tests/test_ec.rs
- rust/tests/test_integration.rs
> Verify checksums on read

- rust-toolchain.toml
This PR will add rust-toolchain to simplify the setup.
> chore: Add rust-toolchain

- LICENSE
Close https://github.com/Kimahriman/hdfs-native/issues/50
> chore: License project under Apache 2.0

- Cargo.lock
- crates/hdfs-native-object-store/Cargo.toml
- crates/hdfs-native-object-store/src/lib.rs
- crates/hdfs-native-object-store/tests/test_object_store.rs
- crates/hdfs-native/src/hdfs/proxy.rs
> Bump object store version

- crates/hdfs-native/src/client.rs
- crates/hdfs-native/src/file.rs
- crates/hdfs-native/src/hdfs/protocol.rs
- crates/hdfs-native/tests/test_write_resiliency.rs
> Add lease renewing

- Cargo.lock
- README.md
- crates/hdfs-native/Cargo.toml
- crates/hdfs-native/src/security/digest.rs
- crates/hdfs-native/tests/test_integration.rs
> Add encryption support to token SASL

- crates/hdfs-native/minidfs/src/main/java/main/Main.java
- crates/hdfs-native/src/hdfs/connection.rs
- crates/hdfs-native/src/security/sasl.rs
Part of #89 
Implements the original SASL based data transfer encryption. Still need to implement newer/better AES based encryption
> Support SASL based data transfer encryption

- README.md
- crates/hdfs-native/minidfs/src/main/java/main/Main.java
- crates/hdfs-native/src/client.rs
- crates/hdfs-native/src/file.rs
- crates/hdfs-native/src/hdfs/block_reader.rs
- crates/hdfs-native/src/hdfs/block_writer.rs
- crates/hdfs-native/src/hdfs/connection.rs
- crates/hdfs-native/src/hdfs/protocol.rs
- crates/hdfs-native/src/minidfs.rs
- crates/hdfs-native/src/security/digest.rs
- crates/hdfs-native/src/security/sasl.rs
- crates/hdfs-native/tests/test_integration.rs
- crates/hdfs-native/tests/test_read.rs
- crates/hdfs-native/tests/test_write.rs
Resolves #89 
Adds last method for data transfer encryption, using the legacy forced encryption setting
> Support forced data transfer protection

- python/src/lib.rs
> Fix initializing logging in Python

- rust/src/hdfs/block_reader.rs
> Change replicated reader to eagerly cleanup the DataNode connection

- rust/src/client.rs
- rust/src/common/config.rs
> Update with config constructor to still read config files first

- python/hdfs_native/__init__.py
- python/hdfs_native/_internal.pyi
- python/src/lib.rs
- python/tests/test_integration.py
- rust/src/client.rs
- rust/src/hdfs/protocol.rs
- rust/tests/test_integration.rs
> Add setReplication support

- rust/src/security/gssapi.rs
> Fix GSSAPI dynamic loading

- rust/src/client.rs
> Support looking up default fs if hostname isn't provided

- .github/workflows/python-test.yml
- python/conftest.py
- python/hdfs_native/__init__.py
- python/hdfs_native/_internal.pyi
- python/pyproject.toml
- python/src/lib.rs
- python/tests/test_fsspec.py
- python/tests/test_integration.py
Resolves #145 
Aldo adds dataclass-esque constructor for WriteOptions
> Add reprs for py classes

- README.md
- python/hdfs_native/__init__.py
- python/hdfs_native/_internal.pyi
- python/src/lib.rs
- python/tests/test_integration.py
- rust/src/acl.rs
- rust/src/client.rs
- rust/src/hdfs/protocol.rs
- rust/src/lib.rs
- rust/tests/test_integration.rs
> ACL support

- README.md
add how to install Kerberos  in Windows system
> add how to install Kerberos  in Windows system

- python/hdfs_native/cli.py
- python/src/error.rs
- python/tests/test_cli.py
- python/tests/test_fsspec.py
- rust/src/security/gssapi.rs
> Add chown support

- python/hdfs_native/cli.py
- python/tests/test_cli.py
Resolves https://github.com/Kimahriman/hdfs-native/issues/177
> Add chmod with octal mode support

- python/hdfs_native/cli.py
- python/tests/test_cli.py
> Add put to CLI

- python/hdfs_native/cli.py
- python/tests/test_cli.py
> Add rmdir to CLI

- python/hdfs_native/cli.py
- python/tests/test_cli.py
> Add du to CLI

- rust/src/client.rs
- rust/src/common/config.rs
- rust/src/file.rs
- rust/src/hdfs/block_reader.rs
- rust/src/hdfs/block_writer.rs
- rust/src/hdfs/connection.rs
- rust/src/hdfs/proxy.rs
- rust/src/security/sasl.rs
- rust/src/security/user.rs
> Check is security is enabled for datanode sasl auth

- rust/src/client.rs
- rust/src/file.rs
- rust/src/hdfs/block_reader.rs
- rust/src/hdfs/block_writer.rs
- rust/src/hdfs/connection.rs
- rust/src/hdfs/protocol.rs
- rust/src/hdfs/proxy.rs
- rust/tests/test_integration.rs
> Support running from outside tokio runtime

- rust/src/client.rs
- rust/src/common/config.rs
- rust/src/error.rs
This PR is for part of https://github.com/Kimahriman/hdfs-native/issues/236 - remove some unwrap method calls if could.
> Fix unexpected panic when DTD exists (#236)

- Cargo.lock
- python/Cargo.toml
- python/docs/source/conf.py
- rust/Cargo.toml
- rust/src/client.rs
> Support taking external runtime handle
